# Generated by Django 3.2.16 on 2022-11-05 16:23

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=100, region=None)),
                ('countries', django_countries.fields.CountryField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('letter', models.FileField(default='', upload_to='')),
                ('cv', models.FileField(default='', upload_to='')),
                ('role', models.CharField(choices=[('gis', 'GIS and Remote sensing Expert'), ('se', 'Software Engineer'), ('da', 'Data Analyst')], default='', max_length=100)),
                ('about', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('twitter', 'Twitter'), ('radio', 'Radio'), ('friend', 'Friend')], default='How did you hear about us', max_length=200)),
                ('question1', models.TextField(default='')),
                ('question2', models.TextField(default='')),
                ('question3', models.TextField(default='')),
                ('question4', models.TextField(default='')),
                ('question5', models.TextField(default='')),
                ('question6', models.TextField(default='')),
                ('question7', models.TextField(default='')),
                ('question8', models.TextField(default='')),
                ('question9', models.TextField(default='')),
                ('question10', models.TextField(default='')),
                ('question11', models.TextField(default='')),
                ('question12', models.TextField(default='')),
                ('question13', models.TextField(default='')),
                ('question14', models.TextField(default='')),
                ('question15', models.TextField(default='')),
                ('consider', models.TextField(default='')),
            ],
        ),
    ]
