# Generated by Django 3.2.16 on 2022-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='cv',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='role',
            field=models.CharField(choices=[('gis', 'GIS and Remote sensing Expert'), ('se', 'Software Engineer'), ('da', 'Data Analyst')], default='', max_length=100, null=True),
        ),
    ]
