# Generated by Django 3.2.16 on 2022-11-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221105_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='role',
        ),
    ]
