# Generated by Django 3.2.16 on 2022-11-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_registerform_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='role',
            field=models.CharField(choices=[('gis', 'GIS and Remote sensing Expert'), ('se', 'Software Engineer'), ('da', 'Data Analyst')], default='', max_length=100, null=True),
        ),
    ]
